#pragma once

#include <cmath>
#include <memory>
#include <string>

#include "gtest/gtest.h"

#include "logical_query_plan/abstract_lqp_node.hpp"
#include "operators/abstract_operator.hpp"
#include "scheduler/operator_task.hpp"
#include "types.hpp"

namespace opossum {

class AbstractLQPNode;
class Table;

/**
 * Indicates whether the comparison of two tables should happen order sensitive (Yes) or whether it should just be
 * checked whether both tables contain the same rows, independent of order.
 */
enum class OrderSensitivity { Yes, No };

/**
 * "Strict" enforces that both tables have precisely the same column types, "Lenient" allows float instead of double, double
 * instead of float, long instead of int, int instead of long
 */
enum class TypeCmpMode { Strict, Lenient };

/**
 * When comparing tables generated by Hyrise to those generated by, e.g. SQLite, minor differences are to be expected
 * (since sqlite uses double for arithmetics, Hyrise might use float) so for large numbers
 * FloatComparisonMode::RelativeDifference is better since it allows derivation independent of the absolute value.
 * When checking against manually generated tables, FloatComparisonMode::AbsoluteDifference is the better choice.
 */
enum class FloatComparisonMode { RelativeDifference, AbsoluteDifference };

// @{
/**
 * Functions implementing the functionality of our custom macros defined at the bottom of this file.
 */

bool check_table_equal(const std::shared_ptr<const Table>& opossum_table,
                       const std::shared_ptr<const Table>& expected_table, OrderSensitivity order_sensitivity,
                       TypeCmpMode type_cmp_mode, FloatComparisonMode float_comparison_mode);

// @}

bool check_lqp_tie(const std::shared_ptr<const AbstractLQPNode>& output, LQPInputSide input_side,
                   const std::shared_ptr<const AbstractLQPNode>& input);

template <typename Functor>
bool contained_in_lqp(const std::shared_ptr<AbstractLQPNode>& node, Functor contains_fn) {
  if (node == nullptr) return false;
  if (contains_fn(node)) return true;
  return contained_in_lqp(node->left_input(), contains_fn) || contained_in_lqp(node->right_input(), contains_fn);
}

template <typename Functor>
bool contained_in_query_plan(const std::shared_ptr<const AbstractOperator>& node, Functor contains_fn) {
  if (node == nullptr) return false;
  if (contains_fn(node)) return true;
  return contained_in_query_plan(node->input_left(), contains_fn) ||
         contained_in_query_plan(node->input_right(), contains_fn);
}

}  // namespace opossum

/**
 * Compare two tables with respect to OrderSensitivity, TypeCmpMode and FloatComparisonMode
 */
#define EXPECT_TABLE_EQ(opossum_table, expected_table, order_sensitivity, type_cmp_mode, float_comparison_mode) \
  EXPECT_TRUE(                                                                                                  \
      check_table_equal(opossum_table, expected_table, order_sensitivity, type_cmp_mode, float_comparison_mode));

/**
 * Specialised version of EXPECT_TABLE_EQ
 */
#define EXPECT_TABLE_EQ_UNORDERED(opossum_table, expected_table)                            \
  EXPECT_TABLE_EQ(opossum_table, expected_table, OrderSensitivity::No, TypeCmpMode::Strict, \
                  FloatComparisonMode::AbsoluteDifference)

/**
 * Specialised version of EXPECT_TABLE_EQ
 */
#define EXPECT_TABLE_EQ_ORDERED(opossum_table, expected_table)                               \
  EXPECT_TABLE_EQ(opossum_table, expected_table, OrderSensitivity::Yes, TypeCmpMode::Strict, \
                  FloatComparisonMode::AbsoluteDifference)

#define ASSERT_LQP_TIE(output, input_side, input) \
  if (!opossum::check_lqp_tie(output, input_side, input)) FAIL();

#define EXPECT_LQP_EQ(lhs, rhs)                                             \
  {                                                                         \
    const auto mismatch = lqp_find_subplan_mismatch(lhs, rhs);              \
    if (mismatch) {                                                         \
      std::cout << "Differing subtrees" << std::endl;                       \
      std::cout << "-------------- Actual LQP --------------" << std::endl; \
      if (mismatch->first)                                                  \
        mismatch->first->print();                                           \
      else                                                                  \
        std::cout << "NULL" << std::endl;                                   \
      std::cout << std::endl;                                               \
      std::cout << "------------- Expected LQP -------------" << std::endl; \
      if (mismatch->second)                                                 \
        mismatch->second->print();                                          \
      else                                                                  \
        std::cout << "NULL" << std::endl;                                   \
      std::cout << "-------------..............-------------" << std::endl; \
      GTEST_FAIL();                                                         \
    }                                                                       \
  }
