image: hyrise/opossum-ci:16.10

before_script:
  - ./install.sh
  - git submodule update --init

stages:
  - build
  - test_gcc
  - test_clang
  - asan
  - coverage

compile_gcc:
  stage: build
  script:
    - premake4 --compiler=gcc
    - make -j -R

compile_clang:
  stage: build
  script:
    - premake4 --compiler=clang
    - make -j -R

gcc_release:
  stage: test_gcc
  script:
    - premake4 --compiler=gcc
    - make -j -R config=release test

gcc_debug:
  stage: test_gcc
  script:
    - premake4 --compiler=gcc
    - make -j -R config=debug test

clang_release:
  stage: test_clang
  script:
    - premake4 --compiler=clang
    - make -j -R config=release test

clang_debug:
  stage: test_clang
  script:
    - premake4 --compiler=clang
    - make -j -R config=debug test

asan_release:
  stage: asan
  script:
    - premake4 --compiler=clang
    - make -j -R config=release asan

asan_debug:
  stage: asan
  script:
    - premake4 --compiler=clang
    - make -j -R config=debug asan

coverage:
  stage: coverage
  script:
    - premake4
    - make coverage
  artifacts:
    paths:
    - coverage/index.html