version: '2.1'

services:
  hyrise:
    image: hyrise
    build: .
    command: bash -c "bash --rcfile <(echo '. /etc/bash_completion')"
    working_dir: /hyrise
    volumes:
      - ".:/hyrise"
      - "~/.ssh/:/root/.ssh/"
      - "~/.gitconfig:/root/.gitconfig"
