#pragma once

#include <memory>
#include <vector>

#include "scheduler/operator_task.hpp"

namespace opossum {

typedef std::function<std::shared_ptr<AbstractOperator>()> OperatorGenerator;

// Query plan that is generated by the SQLQueryTranslator.
class SQLQueryPlan {
 public:
  SQLQueryPlan();

  // Returns the current size of the query plan.
  size_t size() const;

  // Returns the task that was most recently added to the plan.
  std::shared_ptr<OperatorTask> back() const;

  // Adds a task to the end of the query plan.
  void add_task(std::shared_ptr<OperatorTask> task);

  // Append all tasks from the other plan to this query plan.
  void append(const SQLQueryPlan& other_plan);

  // Remove all tasks from the current plan.
  void clear();

  std::shared_ptr<OperatorTask> task(size_t index) const;

  const std::vector<std::shared_ptr<OperatorTask>>& tasks() const;

  std::vector<std::shared_ptr<OperatorTask>> cloneTasks() const;

 protected:
  std::vector<std::shared_ptr<OperatorTask>> deepCloneTasks(std::shared_ptr<const AbstractOperator> root) const;

  std::vector<std::shared_ptr<OperatorTask>> _tasks;
};

}  // namespace opossum
