# This file was generated by update.sh from the fetchCommit uses in default.nix.
# Do not edit this file by hand. Instead, edit default.nix and run update.sh
{
  "757873b3468a1d413d6776c7f2e83c41c340cb91" = {
    hash = "15m8ksbc65gd8dpm064a7k0mk7aa47ry7gjdn3d4wrc2q25jx2mp";
    path = "/nix/store/wdzzqava3vnz11v6wa7k3gyxg7m1myrg-source";
  };
}
