load src/test/tables/tpch-sf-0001/customer.tbl customer
load src/test/tables/tpch-sf-0001/lineitem.tbl lineitem
load src/test/tables/tpch-sf-0001/nation.tbl nation
load src/test/tables/tpch-sf-0001/orders.tbl orders
load src/test/tables/tpch-sf-0001/part.tbl part
load src/test/tables/tpch-sf-0001/partsupp.tbl partsupp
load src/test/tables/tpch-sf-0001/region.tbl region
load src/test/tables/tpch-sf-0001/supplier.tbl supplier