load resources/test_data/tbl/tpch/sf-0.001/customer.tbl customer
load resources/test_data/tbl/tpch/sf-0.001/lineitem.tbl lineitem
load resources/test_data/tbl/tpch/sf-0.001/nation.tbl nation
load resources/test_data/tbl/tpch/sf-0.001/orders.tbl orders
load resources/test_data/tbl/tpch/sf-0.001/part.tbl part
load resources/test_data/tbl/tpch/sf-0.001/partsupp.tbl partsupp
load resources/test_data/tbl/tpch/sf-0.001/region.tbl region
load resources/test_data/tbl/tpch/sf-0.001/supplier.tbl supplier
    