# This script is used to join and clean the TCPH data for use in the 'cost_models' script
# It takes as arguments the four .csv files that are generated by the TCPH run on hyrise

import pandas as pd
import sys

def import_test_data(tpch):
    # read data
    table_scans = pd.read_csv(tpch[0])
    table_meta_data = pd.read_csv(tpch[1])
    segment_meta_data = pd.read_csv(tpch[2])
    attribute_meta_data = pd.read_csv(tpch[3])

    # preprocess data
    joined_data = table_scans.merge(table_meta_data, on="TABLE_NAME", how="left")
    joined_data = joined_data.merge(attribute_meta_data, on="COLUMN_NAME", how="left")
    joined_data = joined_data.merge(segment_meta_data, on="COLUMN_NAME", how="left")

    joined_data = joined_data[['SCAN_TYPE', 'TABLE_NAME', 'COLUMN_NAME', 'INPUT_ROWS',
                               'OUTPUT_ROWS', 'RUNTIME_NS', 'ROW_COUNT_x',
                               'MAX_CHUNK_SIZE', 'DATA_TYPE',
                               'DISTINCT_VALUE_COUNT', 'IS_NULLABLE',
                               'ENCODING', 'COMPRESSION', 'SIZE_IN_BYTES']]
    joined_data = joined_data.rename(columns={"TABLE_NAME_x": "TABLE_NAME", "ROW_COUNT_x": "ROW_COUNT"})

    joined_data['SELECTIVITY'] = (joined_data['OUTPUT_ROWS'] / joined_data['INPUT_ROWS'])
    joined_data['SELECTIVITY'].fillna(0, inplace=True)

    return joined_data

