#!/bin/bash

if [ -f ./git/MERGE_HEAD ];
then
    exit 0
fi

function finish {
    git stash pop>/dev/null
}
git stash --keep-index >/dev/null && trap finish EXIT
echo Linting all code, this may take a while...

find src -iname *.cpp -o -iname *.hpp | while read line;
do
    if ! python2.7 cpplint.py --verbose=0 --extensions=hpp,cpp --counting=detailed --filter=-legal/copyright,-whitespace/newline,-runtime/references,-build/c++11 --linelength=120 $line >/dev/null 2>/dev/null
    then
        echo ERROR: Linting error occured. Execute \"premake4 lint\" for details!
        exit 1
    fi
done

if [ $? != 0 ]
then
    exit 1
fi

echo Success, no linting errors found!

echo Testing the Opossum, grrrrr...

pushd build >/dev/null
make -j opossumTest >/dev/null 2>/dev/null
popd >/dev/null

if ! ./build/opossumTest >/dev/null 2>/dev/null
then
    echo ERROR: Testing error occured. Execute tests for details!
    exit 1
fi

echo Success, no testing errors found! 
