#ifndef HYRISE_TASKS_PER_STATEMENT
#define HYRISE_TASKS_PER_STATEMENT(...)
#endif
#ifndef HYRISE_SUMMARY
#define HYRISE_SUMMARY(...)
#endif
#ifndef HYRISE_SQL_PARSING
#define HYRISE_SQL_PARSING(...)
#endif
#ifndef HYRISE_CREATE_PIPELINE
#define HYRISE_CREATE_PIPELINE(...)
#endif
#ifndef HYRISE_PIPELINE_CREATION_DONE
#define HYRISE_PIPELINE_CREATION_DONE(...)
#endif
#ifndef HYRISE_SCHEDULE_TASKS
#define HYRISE_SCHEDULE_TASKS(...)
#endif
#ifndef HYRISE_TASKS
#define HYRISE_TASKS(...)
#endif
#ifndef HYRISE_SCHEDULE_TASKS_AND_WAIT
#define HYRISE_SCHEDULE_TASKS_AND_WAIT(...)
#endif
#ifndef HYRISE_JOB_START
#define HYRISE_JOB_START(...)
#endif
#ifndef HYRISE_JOB_END
#define HYRISE_JOB_END(...)
#endif
#ifndef HYRISE_OPERATOR_TASKS
#define HYRISE_OPERATOR_TASKS(...)
#endif
#ifndef HYRISE_OPERATOR_STARTED
#define HYRISE_OPERATOR_STARTED(...)
#endif
#ifndef HYRISE_OPERATOR_EXECUTED
#define HYRISE_OPERATOR_EXECUTED(...)
#endif
