# How to test this locally:
#   In the root of the Hyrise repository, run:
#     nix-shell -p act --run "act"
#   Act is a software that allows you to simulate GitHub Actions CIs locally. It works best in containerized environments.
#   Docker is required to run this as docker-credential-desktop is required, which Nix does not deliver.

name: Nix-Build of Hyrise
on: push

jobs:
  nix-clang-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix - Hyrise Debug Clang Build
        run: |
          nix-shell --pure --run "\
            mkdir nix-cmake-build-debug && cd nix-cmake-build-debug && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && \
            ninja
          "

  nix-clang-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix - Hyrise Release Clang Build
        run: |
          nix-shell --pure --run "\
            mkdir nix-cmake-build-release && cd nix-cmake-build-release && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && \
            ninja
          "
