# How to test this?
#
# In the root of the repository, run:
#   nix-shell -p act --run "act"
# Act is a software that allows you to simulate GitHub Actions CIs locally.
# It works best in container environments that are not self-hosted.
# Docker is required to run this as docker-credential-desktop is required,
# which Nix does not deliver.

name: Nix-Build of Hyrise
on: push

env:
  CLONE_COMMAND: git clone --depth 1 -b $GITHUB_REF_NAME --single-branch --recursive ${{ github.server_url }}/${{ github.repository }}.git /app/hyrise

jobs:
  nix-gcc-debug:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout Repository
        run: |
          mkdir /app/hyrise && cd /app
          nix-shell -p git --run "$CLONE_COMMAND"
      - name: System Stats
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            gcc --version && \
            g++ --version
          "
      - name: Nix - Hyrise Debug Clang Build
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            mkdir nix-cmake-build && cd nix-cmake-build && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .. && \
            ninja
          "
  nix-gcc-release:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout Repository
        run: |
          mkdir /app/hyrise && cd /app
          nix-shell -p git --run "$CLONE_COMMAND"
      - name: Nix - Hyrise RelClang Build
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            mkdir cmake-nix-build && cd cmake-nix-build && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Release .. && \
            ninja
          "
  nix-clang-debug:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout Repository
        run: |
          mkdir /app/hyrise && cd /app
          nix-shell -p git --run "$CLONE_COMMAND"
      - name: System Stats
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            clang --version && \
            clang++ --version
          "
      - name: Nix - Hyrise Debug Clang Build
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            mkdir nix-cmake-build && cd nix-cmake-build && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && \
            ninja
          "
  nix-clang-release:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout Repository
        run: |
          mkdir /app/hyrise && cd /app
          nix-shell -p git --run "$CLONE_COMMAND"
      - name: System Stats
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            clang --version && \
            clang++ --version
          "
      - name: Nix - Hyrise Release Clang Build
        run: |
          cd /app/hyrise
          nix-shell --pure --run "\
            mkdir nix-cmake-build && cd nix-cmake-build && \
            cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && \
            ninja
          "
